[package]
name = "yew-microcms"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
chrono = "0.4"
console_error_panic_hook = { version = "0.1.5", optional = true }
serde = "1"
serde_derive = "1"
yew = "0.17"
yew-router = "0.14.0"
wasm-bindgen = "0.2.67"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Document",
  "Element",
  "Node",
  "Window",
]

[features]
default = ["console_error_panic_hook"]
